# Generated by Django 4.2.2 on 2023-07-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='page',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
