# Generated by Django 4.2.2 on 2023-07-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_exercise_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
