# Generated by Django 4.2.2 on 2023-07-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0003_exercise_link_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='page',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
