# Generated by Django 4.2.2 on 2023-08-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0006_source_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='percent_completed',
        ),
    ]
