# Generated by Django 4.2.2 on 2023-08-01 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice_logs', '0007_remove_exercise_percent_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('name', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('name', 'user')},
        ),
    ]
