# Generated by Django 4.2.2 on 2023-08-02 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0008_alter_source_name_alter_exercise_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice_logs.source'),
        ),
        migrations.AlterField(
            model_name='session',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice_logs.exercise'),
        ),
    ]
