# Generated by Django 4.2.2 on 2023-08-02 19:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0012_alter_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime.today, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 2), message='Please choose a day on or before 2023-08-02 19:58:38.439347')]),
        ),
    ]
