# Generated by Django 4.2.2 on 2023-08-16 21:26

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0016_alter_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice_logs.source'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime.today, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 16), message='Please choose a day on or before today')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice_logs.exercise'),
        ),
    ]
