# Generated by Django 4.2.2 on 2023-09-12 21:58

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice_logs', '0018_alter_session_days_since_last_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime.today, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 12), message='Please choose a day on or before today')]),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.today, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 9, 12), message='Please choose a day on or after today')])),
                ('end_date', models.DateField(default=datetime.datetime.today, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 9, 12), message='Please choose a day on or after today')])),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=8)),
                ('exercise', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='practice_logs.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
