# Generated by Django 4.2.2 on 2023-09-12 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0019_alter_session_date_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='exercise',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='practice_logs.exercise'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=8),
        ),
    ]
