# Generated by Django 4.2.2 on 2023-09-13 01:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0020_alter_goal_exercise_alter_goal_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(default=datetime.datetime.today, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 9, 13), message='Please choose a day on or after today')]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(default=datetime.datetime.today, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 9, 13), message='Please choose a day on or after today')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime.today, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 13), message='Please choose a day on or before today')]),
        ),
    ]
