# Generated by Django 4.2.2 on 2023-09-19 16:27

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice_logs', '0026_exercise_user_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime.today, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 9, 19), message='Please choose a day on or before today')]),
        ),
        migrations.RemoveField(
            model_name='session',
            name='exercise',
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='exercise',
            field=models.ManyToManyField(to='practice_logs.exercise'),
        ),
    ]
