# Generated by Django 4.2.2 on 2023-09-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0027_alter_exercise_user_alter_session_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='exercise',
            new_name='exercises',
        ),
    ]
