# Generated by Django 4.2.2 on 2023-09-21 21:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0028_rename_exercise_session_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='bpm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime.today, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 10, 3), message='Please choose a day on or before today')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='exercises',
            field=models.ManyToManyField(blank=True, null=True, to='practice_logs.exercise'),
        ),
    ]
