# Generated by Django 4.2.2 on 2023-10-05 00:40

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0029_alter_session_bpm_alter_session_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='exercises',
        ),
        migrations.AlterField(
            model_name='session',
            name='bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime.today, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 10, 5), message='Please choose a day on or before today')]),
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice_logs.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice_logs.session')),
            ],
        ),
    ]
