# Generated by Django 4.2.2 on 2023-10-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0030_remove_session_exercises_alter_session_bpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='exercises',
            field=models.ManyToManyField(through='practice_logs.SessionExercise', to='practice_logs.exercise'),
        ),
    ]
