# Generated by Django 4.2.2 on 2023-10-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0031_session_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='bpm',
        ),
    ]
