# Generated by Django 4.2.2 on 2023-10-10 18:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0034_alter_goal_end_date_alter_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(default=datetime.datetime.today, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 10, 17), 'End date must be between a week and a month after the start date'), django.core.validators.MaxValueValidator(datetime.date(2023, 11, 10), 'End date must be between a week and a month after the start date')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime.today, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 10, 10), message='Please choose a day on or before today')]),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='bpm',
            field=models.PositiveIntegerField(),
        ),
    ]
