# Generated by Django 4.2.2 on 2023-10-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0035_alter_goal_end_date_alter_session_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='reminder',
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('complete', 'Completed'), ('in_progress', 'In Progress'), ('expired', 'Expired')], default='in_progress', max_length=11),
        ),
    ]
